#index:
#    path: /
#    controller: App\Controller\DefaultController::index
api_tasks:
    type: rest
    prefix: /api
    resource: App\Controller\TaskController

api_login_check:
    path: /api/login_check
